import PageTransition from '@/components/layouts/PageTransition';
import SEO from '@/components/ui/SEO';

export default function Terms() {
  return (
    <PageTransition>
      <SEO
        title="Terms & Conditions | Merina Builders Construction"
        description="Review the terms, estimates agreements, physical site inspection guidelines, and intellectual property rights of Merina Builders Construction."
        keywords="Terms and Conditions, Merina Builders Terms, Construction Estimates Agreement, Contract Terms"
      />
      <main className="w-full pt-32 pb-24 bg-navy">
        <article className="max-w-3xl mx-auto px-6 text-ivory/80 space-y-6 leading-relaxed font-sans text-sm md:text-base">
          <header className="border-b border-gold/10 pb-6">
            <h1 className="text-3xl md:text-5xl font-bold font-display text-gradient-gold">
              Terms & Conditions
            </h1>
            <p className="text-xs text-muted-foreground mt-2 uppercase tracking-widest font-semibold">
              Last Updated: July 07, 2026
            </p>
          </header>

          <p>
            Welcome to merinabuilders.com. These terms and conditions outline the rules and regulations for the use of Merina Builders\' Website.
          </p>

          <h2 className="text-xl md:text-2xl font-bold font-display text-ivory pt-4">1. Acceptance of Terms</h2>
          <p>
            By accessing this website, we assume you accept these terms and conditions in full. Do not continue to use Merina Builders\' website if you do not accept all of the terms and conditions stated on this page.
          </p>

          <h2 className="text-xl md:text-2xl font-bold font-display text-ivory pt-4">2. Construction Contracts & Estimates</h2>
          <p>
            All budget estimates, project schedules, and specifications provided by our online calculator or AI chatbot are strictly approximate and intended for preliminary planning and reference purposes only.
          </p>
          <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
            <li><strong>AI-Assisted Estimates:</strong> Any cost calculations generated by our AI digital companion (Micky) are reference-only. They do not constitute a legally binding offer, quotation, or contract from our side.</li>
            <li><strong>Final Quotation:</strong> An official, legally binding contract price quote will only be issued after a comprehensive physical site inspection, soil analysis, and detailed structural design engineering reviews are conducted by our engineers.</li>
            <li><strong>Intellectual Property & Rights:</strong> Merina Builders Construction retains full ownership and proprietary rights over all architectural designs, material estimation calculations, and blueprints shared with you during consultations.</li>
          </ul>

          <h2 className="text-xl md:text-2xl font-bold font-display text-ivory pt-4">3. Intellectual Property Rights</h2>
          <p>
            Unless otherwise stated, Merina Builders and/or its licensors own the intellectual property rights for all material on this website, including design templates, architectural renders, blueprints, site photographs, copy, and code. All intellectual property rights are reserved.
          </p>
          <p>
            You must not:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
            <li>Republish material from our website without prior consent</li>
            <li>Sell, rent, or sub-license material from the website</li>
            <li>Reproduce, duplicate, or copy architectural designs or media</li>
            <li>Redistribute content from Merina Builders (unless content is specifically made for redistribution)</li>
          </ul>

          <h2 className="text-xl md:text-2xl font-bold font-display text-ivory pt-4">4. Limitation of Liability</h2>
          <p>
            In no event shall Merina Builders, nor any of its site engineers, architects, or managers, be liable for anything arising out of or in any way connected with your use of this website. Merina Builders shall not be liable for any indirect, consequential, or special liability arising out of or in any way related to your use of this website.
          </p>
        </article>
      </main>
    </PageTransition>
  );
}
